apiVersion: v1
kind: Service
metadata:
  name: employee-management-service
spec:
  selector:
    app: employee-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31127
  type: NodePort
